name: Install Kind Cluster on EC2
run-name: Install Kind on EC2

on:
  workflow_dispatch:
    inputs:
      EC2_IP:
        description: "ip address ec2 intance"
        required: true


jobs:
  install-kind:
    runs-on: self-hosted

    steps:
    - name: Checkout Repo
      uses: action/checkout@v3

    - name: Install Kind on EC2
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ inputs.EC2_IP}}
        username: ec2-user
        key: ${{ secrets.SSH_KEY }}
        port: 22
        script: |
          # TODO: yum update

          # Install Docker
          # TODO

          # Install Kind
          # TODO

          # Install kubectl
          # TODO

          # Create a Kind cluster
          # TODO
